import { expect, test, type Page } from '@playwright/test'

async function reset(page: Page) {
  await page.goto('/brand')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
}

async function switchProfile(page: Page, profile: 'Brand Representative' | 'Community Leader' | 'Community Member') {
  const mobileMenu = page.getByRole('button', { name: 'Open navigation' })
  if (await mobileMenu.isVisible()) await mobileMenu.click()
  await page.locator('.role-switcher').click()
  await page.locator('.role-menu button').filter({ hasText: profile }).click()
}

test.beforeEach(async ({ page }) => reset(page))

test('leadership demonstrates the complete Brand → Leader → Member → Brand workflow', async ({ page }) => {
  test.setTimeout(60000)
  const opportunityName = 'Evidence-Led Skin Week'
  const communityCampaignName = 'Seven-Day Routine Stories'

  await page.goto('/brand/products')
  await page.getByRole('button', { name: /Add product/ }).click()
  await page.getByLabel('Product name').fill('Gentle Gel Cleanser')
  await page.getByLabel('Description').fill('A straightforward daily cleanser for simple routines.')
  await page.getByLabel('Key benefits').fill('Gentle daily cleanse, Lightweight rinse')
  await page.getByRole('button', { name: 'Save product' }).click()
  await expect(page.getByRole('heading', { name: 'Gentle Gel Cleanser' })).toBeVisible()

  await page.goto('/brand/opportunities/new')
  await page.getByLabel('Campaign name').fill(opportunityName)
  await page.getByLabel('Product').selectOption({ label: 'Gentle Gel Cleanser' })
  await page.getByRole('button', { name: /Continue/ }).click()
  await expect(page.getByRole('heading', { name: 'Timing and pool' })).toBeVisible()
  await page.getByRole('button', { name: /Continue/ }).click()
  await expect(page.getByRole('heading', { name: 'Campaign brief' })).toBeVisible()
  await page.getByRole('button', { name: /Continue/ }).click()
  await expect(page.getByRole('heading', { name: 'Review and post' })).toBeVisible()
  await page.getByRole('button', { name: 'Post', exact: true }).click()
  await expect(page.getByRole('heading', { name: opportunityName })).toBeVisible()

  await switchProfile(page, 'Community Leader')
  await expect(page.getByRole('heading', { name: /Good morning, Mara/ })).toBeVisible()
  await page.goto('/leader/opportunities')
  await page.locator('.opportunity-card').filter({ hasText: opportunityName }).click()
  await expect(page.getByText('YOUR AUTOMATIC ALLOCATION')).toBeVisible()
  await expect(page.locator('.claim-panel')).toContainText('150')
  await expect(page.locator('.claim-panel')).toContainText('₱75,000')
  await page.getByRole('button', { name: /Confirm claim/ }).click()
  await expect(page.getByText('ALLOCATION CONFIRMED')).toBeVisible()
  await expect(page.getByText(/No brand response is required/)).toBeVisible()

  await page.goto('/leader/campaigns')
  const allocation = page.locator('.allocation-strip article').filter({ hasText: opportunityName })
  await allocation.getByRole('button', { name: /Create promotion/ }).click()
  await page.getByLabel('Promotion title').fill(communityCampaignName)
  await page.getByRole('button', { name: 'Create draft promotion' }).click()
  const campaignCard = page.locator('.community-campaign-card').filter({ hasText: communityCampaignName })
  await expect(campaignCard).toBeVisible()
  await campaignCard.click()
  await page.getByRole('tab', { name: /^Members/ }).click()
  await page.getByRole('button', { name: /Assign member/ }).click()
  await page.getByLabel('Community member').selectOption('member-maya')
  await page.getByLabel('Assigned content quantity').fill('1')
  await page.getByRole('button', { name: 'Assign member' }).last().click()
  await expect(page.getByText('Maya Reyes')).toBeVisible()
  await expect(page.getByText('Invited')).toBeVisible()

  await switchProfile(page, 'Community Member')
  await expect(page.getByRole('heading', { name: /Keep your campaign work moving, Maya/ })).toBeVisible()
  await page.goto('/member/campaigns')
  await page.locator('.member-campaign-card').filter({ hasText: communityCampaignName }).click()
  await page.getByRole('button', { name: /Accept participation/ }).click()
  await expect(page.getByText(/You've been invited/)).toHaveCount(0)
  await page.goto('/member/content')
  const memberContent = page.locator('.member-content-list article').filter({ hasText: communityCampaignName })
  await memberContent.getByRole('button', { name: /Mark in progress/ }).click()
  await memberContent.getByRole('button', { name: /Mark published/ }).click()
  await memberContent.getByRole('button', { name: /Record published link/ }).click()
  await page.getByLabel('Published-content URL').fill('https://www.tiktok.com/@mayareyes/video/evidence-week')
  await page.getByRole('button', { name: /Record content/ }).click()
  await expect(memberContent.getByText('Recorded', { exact: true })).toBeVisible()
  await expect(memberContent.getByText(/Waiting for Community Leader validation/)).toBeVisible()

  await switchProfile(page, 'Community Leader')
  await page.goto('/leader/content')
  const contentRow = page.locator('tbody tr').filter({ hasText: communityCampaignName })
  await contentRow.getByRole('button', { name: /Validate & count/ }).click()
  await expect(contentRow.locator('.status-badge').getByText('Counted', { exact: true })).toBeVisible()

  await switchProfile(page, 'Brand Representative')
  await page.goto('/brand/opportunities')
  const brandCampaign = page.locator('.campaign-portfolio-card').filter({ hasText: opportunityName })
  await brandCampaign.locator('summary').click()
  await brandCampaign.getByRole('link', { name: /View campaign/ }).click()
  await page.getByRole('tab', { name: /Content/ }).click()
  const brandRow = page.locator('tbody tr').filter({ hasText: communityCampaignName })
  await expect(brandRow.getByText('Counted', { exact: true })).toBeVisible()
  await expect(brandRow.getByText('SkinTok PH')).toBeVisible()

  await page.goto('/brand/reports')
  await page.getByRole('link', { name: /Hydration, Your Way/ }).click()
  await expect(page.getByText('Campaign completion report')).toBeVisible()
  await expect(page.getByText('Published-content commitment fulfilled')).toBeVisible()
})

test('allocation preview is proportional, fixed, and has no Brand approval controls', async ({ page }) => {
  await switchProfile(page, 'Community Leader')
  await page.goto('/leader/opportunities/opportunity-barrier-reset')
  await expect(page.getByText('YOUR AUTOMATIC ALLOCATION')).toBeVisible()
  await expect(page.locator('.claim-panel')).toContainText('60')
  await expect(page.locator('.claim-panel')).toContainText('₱60,000')
  await expect(page.getByText(/Dates, quota, and budget cannot be changed or negotiated/)).toBeVisible()
  await page.getByRole('button', { name: /Confirm claim/ }).click()
  await expect(page.getByText(/No brand response is required/)).toBeVisible()
  await page.reload()
  await expect(page.getByText('ALLOCATION CONFIRMED')).toBeVisible()
})

test('preparation is separate, persisted, and advances readiness', async ({ page }) => {
  await switchProfile(page, 'Community Leader')
  await page.goto('/leader/campaigns/cc-sun-prep?tab=preparation')
  await expect(page.getByText(/do not count toward the content commitment/)).toBeVisible()
  const monitoring = page.getByRole('button', { name: /Monitoring ready/ })
  await monitoring.click()
  await page.getByRole('button', { name: /Promotion ready to launch/ }).click()
  await page.reload()
  await expect(page.getByText('Ready', { exact: true }).first()).toBeVisible()
})

test('Member workspace is responsive and reset restores deterministic demo data', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await switchProfile(page, 'Community Member')
  await expect(page.getByRole('heading', { name: /Keep your campaign work moving, Maya/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Open navigation' })).toBeVisible()
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await expect(page.getByRole('link', { name: 'My Content' })).toBeVisible()
  await page.getByRole('button', { name: /Reset demo data/ }).click()
  await page.goto('/brand/opportunities')
  await expect(page.locator('.campaign-portfolio-card')).toHaveCount(6)
})
