import {
  ArrowLeft, ArrowRight, BadgeCheck, BarChart3, Check, CheckCircle2, CircleDollarSign,
  Layers3, Library, LockKeyhole, Plus, ShieldCheck, Target, UserCheck, UserPlus,
  Users, WalletCards,
} from 'lucide-react'
import { useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import {
  Avatar, Callout, CheckRow, ContentBadge, EmptyState, MetricCard, OpportunityCard, PageHeader,
  Panel, ProgressBar, SegmentedTabs, StatusBadge,
} from '../components'
import {
  calculateAllocation, formatCurrency, formatDate, formatNumber, getCommunityCampaignMetrics,
  getOpportunityMetrics, useApp,
} from '../store'
import { madridPromotions } from '../madridPromotions'
import type { Community, CommunityCampaign, CommunityClaim } from '../types'

function useLeaderContext() {
  const app = useApp()
  const community = app.state.communities.find((item) => item.leaderId === app.state.activeLeaderId) ?? app.state.communities[0]
  const memberIds = new Set(app.state.members.filter((item) => item.communityId === community.id).map((item) => item.id))
  const claims = app.state.claims.filter((item) => item.communityId === community.id)
  const campaigns = app.state.communityCampaigns.filter((item) => item.communityId === community.id)
  const assignments = app.state.assignments.filter((item) => memberIds.has(item.memberId))
  const contents = app.state.contents.filter((item) => memberIds.has(item.memberId))
  return { ...app, community, claims, campaigns, assignments, contents }
}

function claimRemaining(state: ReturnType<typeof useApp>['state'], claim: CommunityClaim) {
  const campaigns = state.communityCampaigns.filter((item) => item.claimId === claim.id)
  return {
    content: claim.contentQuota - campaigns.reduce((sum, item) => sum + item.contentQuota, 0),
    budget: claim.budgetAllocation - campaigns.reduce((sum, item) => sum + item.rewardBudget, 0),
  }
}

export function LeaderDashboard() {
  const { state, community, claims, campaigns, contents } = useLeaderContext()
  const assignedQuota = claims.reduce((sum, item) => sum + item.contentQuota, 0)
  const counted = contents.filter((item) => item.status === 'Counted').length
  const communityEarnings = madridPromotions.slice(0, 4).reduce((sum, promotion) => sum + promotion.earnings, 0)
  const open = state.opportunities.filter((item) => ['Open', 'Partially Claimed'].includes(item.status) && !claims.some((claim) => claim.opportunityId === item.id))
  return <div className="page-stack">
    <PageHeader eyebrow="COMMUNITY MANAGER" title={`Good morning, ${community.leaderName.split(' ')[0]}.`} description={`Turn ${community.verifiedSize} verified creators into accountable campaign delivery.`} actions={<Link to="/leader/opportunities" className="button button-primary"><Library size={16} />Browse campaigns</Link>} />
    <section className="leader-identity-banner"><Avatar initials={community.initials} size="lg" tone="mint" /><div><span className="eyebrow">REGISTERED COMMUNITY</span><h2>{community.name}</h2><p>{community.location} · {community.leaderType} Community Manager</p></div><div className="verified-size"><BadgeCheck size={20} /><span><strong>{community.verifiedSize}</strong>verified creators</span></div></section>
    <section className="metrics-grid metrics-grid-three"><MetricCard label="Assigned quota" value={assignedQuota} detail={`${claims.length} brand allocations`} icon={Target} /><MetricCard label="Counted content" value={counted} detail={`${assignedQuota ? Math.round(counted / assignedQuota * 100) : 0}% community fulfillment`} icon={CheckCircle2} tone="yellow" /><MetricCard label="Total community earnings" value={formatCurrency(communityEarnings)} detail="across active promotions" icon={CircleDollarSign} /></section>
    <div className="two-column-layout wide-left"><Panel title="My promotions" description="Live Madrid Philippines promotions managed by your community." action={<Link to="/leader/campaigns" className="text-link">Manage all</Link>}><div className="leader-promotion-list">{madridPromotions.slice(0, 4).map((promotion) => <article key={promotion.id} className="leader-promotion-row"><img src={promotion.src} alt="" /><div><strong>{promotion.name}</strong><small>{promotion.manager} · {formatNumber(promotion.views)} views</small></div><b>{formatCurrency(promotion.earnings)}</b></article>)}</div></Panel><Panel title="Open campaigns" description="Claim with your verified community."><div className="mini-opportunity-list">{open.slice(0, 3).map((opportunity) => { const preview = calculateAllocation(state, opportunity.id, community.id); return <Link key={opportunity.id} to={`/leader/opportunities/${opportunity.id}`}><div><span>{opportunity.platform}</span><strong>{opportunity.name}</strong><small>{preview.contentQuota} contents · {formatCurrency(preview.budgetAllocation)}</small></div><ArrowRight size={16} /></Link> })}{open.length === 0 ? <EmptyState title="No open campaigns" description="New brand campaigns will appear here." /> : null}</div></Panel></div>
    <Panel title="Community delivery pulse"><div className="delivery-pulse">{campaigns.filter((item) => item.status !== 'Completed').map((campaign) => { const metrics = getCommunityCampaignMetrics(state, campaign.id); return <div key={campaign.id}><div><strong>{campaign.title}</strong><span>{metrics.counted}/{campaign.contentQuota} counted</span></div><ProgressBar value={metrics.completionPercentage} /><small>{metrics.remaining} remaining · deadline {formatDate(campaign.deadline)}</small></div> })}</div></Panel>
  </div>
}

export function LeaderOpportunities() {
  const { state, community, claims } = useLeaderContext()
  const open = state.opportunities.filter((item) => ['Open', 'Partially Claimed'].includes(item.status) && !claims.some((claim) => claim.opportunityId === item.id))
  const claimed = claims.map((claim) => state.opportunities.find((item) => item.id === claim.opportunityId)).filter(Boolean)
  return <div className="page-stack"><PageHeader eyebrow="CAMPAIGN MARKETPLACE" title="Campaigns your community can power" description={`Every preview uses ${community.name}’s verified size of ${community.verifiedSize} creators. No applications or negotiation.`} /><Callout title="Claim means confirmed">Review the fixed dates, remaining capacity, content quota, and budget allocation. Confirmation creates the allocation immediately—brands do not approve or reject claims.</Callout><Panel title="Open for claiming" description={`${open.length} campaigns currently have capacity.`}><div className="opportunity-grid">{open.map((opportunity) => { const product = state.products.find((item) => item.id === opportunity.productId)!; const preview = calculateAllocation(state, opportunity.id, community.id); return <OpportunityCard key={opportunity.id} id={opportunity.id} name={opportunity.name} product={product.name} platform={opportunity.platform} status={opportunity.status} content={`${preview.contentQuota} content allocation`} budget={formatCurrency(preview.budgetAllocation)} dates={`${formatDate(opportunity.liveStart)} – ${formatDate(opportunity.liveEnd)}`} to={`/leader/opportunities/${opportunity.id}`} /> })}{open.length === 0 ? <EmptyState icon={Library} title="No claimable campaigns" description="This community has claimed every currently available campaign." /> : null}</div></Panel><Panel title="Claimed by your community" description="Allocations are fixed and ready to turn into promotions."><div className="claimed-list">{claimed.map((opportunity) => { const claim = claims.find((item) => item.opportunityId === opportunity!.id)!; return <Link key={opportunity!.id} to={`/leader/opportunities/${opportunity!.id}`}><span className="claim-check"><Check size={15} /></span><div><strong>{opportunity!.name}</strong><p>{claim.contentQuota} contents · {formatCurrency(claim.budgetAllocation)} · claimed {claim.claimedAt}</p></div><StatusBadge status={opportunity!.status} /><ArrowRight size={16} /></Link> })}</div></Panel></div>
}

export function LeaderOpportunityDetail() {
  const { state, dispatch, community, claims } = useLeaderContext()
  const { opportunityId } = useParams()
  const opportunity = state.opportunities.find((item) => item.id === opportunityId)
  const [confirmed, setConfirmed] = useState(false)
  if (!opportunity) return <EmptyState title="Campaign not found" description="Return to the campaign marketplace." />
  const product = state.products.find((item) => item.id === opportunity.productId)!
  const existingClaim = claims.find((item) => item.opportunityId === opportunity.id)
  const preview = calculateAllocation(state, opportunity.id, community.id)
  const metrics = getOpportunityMetrics(state, opportunity.id)
  const claimOpportunityId = opportunity.id
  function claim() { dispatch({ type: 'CLAIM_OPPORTUNITY', opportunityId: claimOpportunityId, communityId: community.id }); setConfirmed(true) }
  const currentClaim = existingClaim ?? (confirmed ? { contentQuota: preview.contentQuota, budgetAllocation: preview.budgetAllocation, claimedAt: 'Just now' } : null)
  return <div className="page-stack"><Link className="back-link" to="/leader/opportunities"><ArrowLeft size={15} />Campaign marketplace</Link><header className="opportunity-detail-hero"><div><span className="eyebrow">{opportunity.platform} CAMPAIGN</span><div className="workspace-title-line"><h1>{opportunity.name}</h1><StatusBadge status={opportunity.status} /></div><p>{product.name}</p></div><div className="hero-commitment"><span>Brand commitment</span><strong>{opportunity.requiredContent}</strong><small>published contents</small></div></header>
    <div className="detail-layout"><div className="detail-main"><Panel title="Campaign foundation"><div className="detail-grid"><div><span>Objective</span><strong>{opportunity.objective}</strong></div><div><span>Platform</span><strong>{opportunity.platform}</strong></div><div><span>Preparation</span><strong>{formatDate(opportunity.preparationStart)} – {formatDate(opportunity.preparationEnd)}</strong><small>{opportunity.preparationDays} fixed days</small></div><div><span>Live campaign</span><strong>{formatDate(opportunity.liveStart)} – {formatDate(opportunity.liveEnd)}</strong><small>{opportunity.liveDays} fixed days</small></div></div></Panel><Panel title="Product information"><div className="product-brief"><span className="product-mini-art">DR</span><div><h3>{product.name}</h3><p>{product.description}</p><ul className="clean-list">{product.keyBenefits.map((item) => <li key={item}><Check size={14} />{item}</li>)}</ul><small><strong>Use:</strong> {product.usage}</small></div></div></Panel><Panel title="Content direction"><p className="body-copy">{opportunity.contentDirection}</p><h3>Priority messages</h3><ul className="clean-list">{opportunity.priorityMessages.map((item) => <li key={item}><Check size={14} />{item}</li>)}</ul><div className="tag-row">{[...opportunity.hashtags, ...opportunity.mentions].map((item) => <span key={item}>{item}</span>)}</div></Panel></div>
      <aside className="claim-panel">{currentClaim ? <><span className="success-seal"><Check size={22} /></span><span className="eyebrow">ALLOCATION CONFIRMED</span><h2>{community.name}</h2><p>The system created this allocation immediately. No brand response is required.</p><dl><div><dt>Content quota</dt><dd>{currentClaim.contentQuota}</dd></div><div><dt>Budget allocation</dt><dd>{formatCurrency(currentClaim.budgetAllocation)}</dd></div><div><dt>Campaign dates</dt><dd>Fixed</dd></div><div><dt>Claim status</dt><dd>Confirmed</dd></div></dl><Link className="button button-dark button-block" to="/leader/campaigns"><Plus size={16} />Create promotion</Link></> : <><span className="eyebrow">YOUR AUTOMATIC ALLOCATION</span><h2>{community.name}</h2><div className="verified-formula"><span><strong>{preview.verifiedSize}</strong> verified creators</span><i>÷</i><span><strong>{preview.totalVerifiedSize}</strong> total verified</span></div><dl><div className="claim-highlight"><dt>Content quota</dt><dd>{preview.contentQuota}</dd></div><div className="claim-highlight"><dt>Budget allocation</dt><dd>{formatCurrency(preview.budgetAllocation)}</dd></div><div><dt>Remaining campaign capacity</dt><dd>{preview.remainingContentBeforeClaim}</dd></div><div><dt>Remaining campaign budget</dt><dd>{formatCurrency(preview.remainingBudgetBeforeClaim)}</dd></div></dl><Callout tone="neutral" title="Fixed on confirmation">Dates, quota, and budget cannot be changed or negotiated after claiming.</Callout><button className="button button-primary button-block" onClick={claim} disabled={preview.contentQuota <= 0}><ShieldCheck size={16} />Confirm claim</button><small className="claim-note">Confirmation is immediate. This is not an application.</small></>}</aside>
    </div><Panel title="Current campaign capacity"><div className="capacity-bar"><div><span>Allocated</span><strong>{metrics.allocated} / {metrics.required}</strong></div><ProgressBar value={Math.round(metrics.allocated / metrics.required * 100)} tone="black" /><p>{Math.max(0, metrics.required - metrics.allocated)} content slots remain available across registered communities.</p></div></Panel></div>
}

export function LeaderCampaigns() {
  const { state, claims, campaigns } = useLeaderContext()
  const [creatingFor, setCreatingFor] = useState<CommunityClaim | null>(null)
  return <div className="page-stack"><PageHeader eyebrow="MY PROMOTIONS" title="Turn campaign allocations into promotions" description="Create one or more creator promotions without exceeding the assigned quota or earnings pool." actions={<button className="button button-primary" onClick={() => setCreatingFor(claims.find((claim) => claimRemaining(state, claim).content > 0) ?? null)} disabled={!claims.some((claim) => claimRemaining(state, claim).content > 0)}><Plus size={16} />Create promotion</button>} /><div className="allocation-strip">{claims.map((claim) => { const opportunity = state.opportunities.find((item) => item.id === claim.opportunityId)!; const remaining = claimRemaining(state, claim); return <article key={claim.id}><div><span>{opportunity.name}</span><StatusBadge status={opportunity.status} /></div><dl><div><dt>Assigned</dt><dd>{claim.contentQuota} / {formatCurrency(claim.budgetAllocation)}</dd></div><div><dt>Available to divide</dt><dd>{remaining.content} / {formatCurrency(remaining.budget)}</dd></div></dl>{remaining.content > 0 ? <button className="text-link" onClick={() => setCreatingFor(claim)}><Plus size={14} />Create promotion</button> : <span className="fully-divided"><Check size={14} />Fully divided</span>}</article> })}</div><div className="community-campaign-grid">{campaigns.map((campaign) => { const opportunity = state.opportunities.find((item) => item.id === campaign.opportunityId)!; const metrics = getCommunityCampaignMetrics(state, campaign.id); return <Link to={`/leader/campaigns/${campaign.id}`} className="community-campaign-card" key={campaign.id}><header><span className="campaign-mark">PR</span><StatusBadge status={campaign.status} /></header><span className="overline">{opportunity.name}</span><h2>{campaign.title}</h2><p>{campaign.instructions}</p><div className="campaign-card-metrics"><div><span>Quota</span><strong>{campaign.contentQuota}</strong></div><div><span>Counted</span><strong>{metrics.counted}</strong></div><div><span>Creators</span><strong>{metrics.members}</strong></div><div><span>Earnings</span><strong>{formatCurrency(campaign.rewardBudget)}</strong></div></div><ProgressBar value={metrics.completionPercentage} label="Content completion" /><span className="card-link">Manage promotion <ArrowRight size={15} /></span></Link> })}</div>{creatingFor ? <CreateCommunityCampaignModal claim={creatingFor} onClose={() => setCreatingFor(null)} /> : null}</div>
}

function CreateCommunityCampaignModal({ claim, onClose }: { claim: CommunityClaim; onClose: () => void }) {
  const { state, dispatch } = useApp()
  const opportunity = state.opportunities.find((item) => item.id === claim.opportunityId)!
  const remaining = claimRemaining(state, claim)
  const [form, setForm] = useState({ title: '', themes: 'Real routines, Product application', instructions: '', memberRequirements: '', deadline: opportunity.liveEnd, contentQuota: Math.min(remaining.content, 20), rewardBudget: Math.min(remaining.budget, 20000) })
  const valid = form.title.trim() && form.contentQuota > 0 && form.contentQuota <= remaining.content && form.rewardBudget >= 0 && form.rewardBudget <= remaining.budget
  function submit(event: React.FormEvent) { event.preventDefault(); if (!valid) return; dispatch({ type: 'CREATE_COMMUNITY_CAMPAIGN', payload: { claimId: claim.id, opportunityId: claim.opportunityId, communityId: claim.communityId, title: form.title, themes: form.themes.split(',').map((item) => item.trim()).filter(Boolean), instructions: form.instructions, memberRequirements: form.memberRequirements, deadline: form.deadline, contentQuota: form.contentQuota, rewardBudget: form.rewardBudget } }); onClose() }
  return <div className="modal-backdrop"><form className="modal-card form-modal" onSubmit={submit}><header><div><span className="eyebrow">UNDER {opportunity.name.toUpperCase()}</span><h2>Create promotion</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></header><div className="available-allocation"><div><span>Available content</span><strong>{remaining.content}</strong></div><div><span>Available earnings</span><strong>{formatCurrency(remaining.budget)}</strong></div><LockKeyhole size={20} /></div><div className="form-grid form-grid-two"><label className="field full"><span>Promotion title</span><input aria-label="Promotion title" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="e.g. 7-Day Barrier Diaries" /></label><label className="field full"><span>Content themes</span><input value={form.themes} onChange={(event) => setForm({ ...form, themes: event.target.value })} /><small>Separate themes with commas.</small></label><label className="field full"><span>Publishing instructions</span><textarea rows={3} value={form.instructions} onChange={(event) => setForm({ ...form, instructions: event.target.value })} /></label><label className="field full"><span>Creator content requirements</span><textarea rows={3} value={form.memberRequirements} onChange={(event) => setForm({ ...form, memberRequirements: event.target.value })} /></label><label className="field"><span>Internal deadline</span><input type="date" min={opportunity.liveStart} max={opportunity.liveEnd} value={form.deadline} onChange={(event) => setForm({ ...form, deadline: event.target.value })} /></label><span /><label className="field"><span>Content quota</span><input aria-label="Promotion content quota" type="number" min="1" max={remaining.content} value={form.contentQuota} onChange={(event) => setForm({ ...form, contentQuota: Number(event.target.value) })} /><small>Maximum {remaining.content}</small></label><label className="field"><span>Earnings allocation</span><div className="money-input"><span>₱</span><input aria-label="Promotion earnings allocation" type="number" min="0" max={remaining.budget} value={form.rewardBudget} onChange={(event) => setForm({ ...form, rewardBudget: Number(event.target.value) })} /></div><small>Maximum {formatCurrency(remaining.budget)}</small></label></div><Callout tone="neutral" title="Allocation guardrail">OkPo blocks content and earnings totals above this community’s assigned quota and pool.</Callout><footer><button type="button" className="button button-secondary" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={!valid}>Create draft promotion</button></footer></form></div>
}

export function LeaderCampaignWorkspace() {
  const { state, dispatch, community } = useLeaderContext()
  const { communityCampaignId } = useParams()
  const [params, setParams] = useSearchParams()
  const campaign = state.communityCampaigns.find((item) => item.id === communityCampaignId)
  const tab = params.get('tab') ?? 'overview'
  const [assigning, setAssigning] = useState(false)
  if (!campaign || campaign.communityId !== community.id) return <EmptyState title="Promotion not found" description="Return to your promotions." />
  const opportunity = state.opportunities.find((item) => item.id === campaign.opportunityId)!
  const claim = state.claims.find((item) => item.id === campaign.claimId)!
  const metrics = getCommunityCampaignMetrics(state, campaign.id)
  const assignments = state.assignments.filter((item) => item.communityCampaignId === campaign.id)
  const content = state.contents.filter((item) => item.communityCampaignId === campaign.id)
  const tabs = [{ id: 'overview', label: 'Overview' }, { id: 'preparation', label: 'Preparation' }, { id: 'members', label: 'My creators', count: metrics.members }, { id: 'content', label: 'Content', count: metrics.recorded }, { id: 'budget', label: 'Earnings' }]
  return <div className="page-stack workspace-page"><Link className="back-link" to="/leader/campaigns"><ArrowLeft size={15} />My promotions</Link><header className="workspace-header"><div className="workspace-mark mint-mark">PR</div><div><div className="workspace-title-line"><h1>{campaign.title}</h1><StatusBadge status={campaign.status} /></div><p>{opportunity.name}</p><span>{community.name} · deadline {formatDate(campaign.deadline)}</span></div><div className="workspace-actions">{campaign.status !== 'Completed' ? <button className="button button-primary" onClick={() => dispatch({ type: 'ADVANCE_COMMUNITY_CAMPAIGN', communityCampaignId: campaign.id })}>Advance to next phase <ArrowRight size={16} /></button> : null}</div></header><SegmentedTabs tabs={tabs} active={tab} onChange={(id) => setParams({ tab: id })} />
    {tab === 'overview' ? <div className="tab-stack"><section className="metrics-grid metrics-grid-four"><MetricCard label="Content quota" value={campaign.contentQuota} detail={`of ${claim.contentQuota} community allocation`} icon={Target} /><MetricCard label="Assigned" value={metrics.assigned} detail={`${Math.max(0, campaign.contentQuota - metrics.assigned)} slots available`} icon={Users} /><MetricCard label="Counted" value={metrics.counted} detail={`${metrics.completionPercentage}% complete`} icon={CheckCircle2} tone="yellow" /><MetricCard label="Earnings allocation" value={formatCurrency(campaign.rewardBudget)} detail={`within ${formatCurrency(claim.budgetAllocation)}`} icon={CircleDollarSign} /></section><Panel title="Delivery against quota"><div className="commitment-head"><div><h2>{metrics.counted} of {campaign.contentQuota} counted</h2><p>Content contributes after the creator publishes and records the public link.</p></div><strong>{metrics.completionPercentage}%</strong></div><ProgressBar value={metrics.completionPercentage} tone="black" /></Panel><div className="two-column-layout"><Panel title="Operational brief"><h3>Content themes</h3><div className="tag-row">{campaign.themes.map((item) => <span key={item}>{item}</span>)}</div><h3>Publishing instructions</h3><p className="body-copy">{campaign.instructions}</p><h3>Creator requirements</h3><p className="body-copy">{campaign.memberRequirements}</p></Panel><Panel title="Fixed Brand foundation"><dl className="summary-list"><div><dt>Platform</dt><dd>{opportunity.platform}</dd></div><div><dt>Live dates</dt><dd>{formatDate(opportunity.liveStart)} – {formatDate(opportunity.liveEnd)}</dd></div><div><dt>Brand target</dt><dd>{opportunity.requiredContent} contents</dd></div><div><dt>Community quota</dt><dd>{claim.contentQuota} contents</dd></div></dl><div className="locked-note"><LockKeyhole size={16} /><span>Timeline, Brand expectations, and allocation are fixed.</span></div></Panel></div></div> : null}
    {tab === 'preparation' ? <div className="tab-stack"><Callout title="Preparation is separate from live delivery">These readiness tasks happen before publishing begins and do not count toward the content commitment.</Callout><Panel title="Launch readiness" description="Complete each operational check before the promotion goes live."><div className="preparation-grid">{([
      ['membersActivated', 'Community creators activated', 'Creators are active and ready to accept assignments.'],
      ['productAssignmentsReady', 'Product assignments ready', 'Creators know which product they will feature.'],
      ['instructionsPublished', 'Campaign instructions published', 'The complete brief is available to assigned creators.'],
      ['contentThemesPrepared', 'Content themes prepared', 'Operational themes have been divided clearly.'],
      ['monitoringReady', 'Monitoring ready', 'Published-link recording and campaign tracking are ready.'],
      ['readyToLaunch', 'Promotion ready to launch', 'Final readiness confirmation.'],
    ] as const).map(([key, label, description]) => <CheckRow key={key} checked={campaign.preparation[key]} onClick={() => dispatch({ type: 'TOGGLE_PREPARATION', communityCampaignId: campaign.id, key })}><strong>{label}</strong><small>{description}</small></CheckRow>)}</div><div className="readiness-footer"><ProgressBar value={Math.round(Object.values(campaign.preparation).filter(Boolean).length / 6 * 100)} label="Preparation progress" /><span>{Object.values(campaign.preparation).filter(Boolean).length} of 6 ready</span></div></Panel></div> : null}
    {tab === 'members' ? <div className="tab-stack"><Panel title="Assigned creators" description={`${metrics.assigned} of ${campaign.contentQuota} content requirements assigned.`} action={<button className="button button-primary button-small" onClick={() => setAssigning(true)} disabled={metrics.assigned >= campaign.contentQuota}><UserPlus size={15} />Assign creator</button>}><div className="table-wrap"><table><thead><tr><th>Creator</th><th>Joined</th><th>Required content</th><th>Accepted</th><th>Recorded</th><th>Counted</th></tr></thead><tbody>{assignments.map((assignment) => { const member = state.members.find((item) => item.id === assignment.memberId)!; const rows = content.filter((item) => item.assignmentId === assignment.id); return <tr key={assignment.id}><td><div className="person-cell"><Avatar initials={member.initials} size="sm" /><span><strong>{member.name}</strong><small>{member.handle}{member.newlyRecruited ? ' · Newly recruited' : ''}</small></span></div></td><td>{assignment.assignedAt}</td><td>{assignment.requiredContent}</td><td>{assignment.accepted ? <span className="yes-cell"><Check size={14} />Accepted</span> : <StatusBadge status="Invited" />}</td><td>{rows.filter((item) => ['Recorded', 'Validated', 'Counted'].includes(item.status)).length}</td><td>{rows.filter((item) => item.status === 'Counted').length}</td></tr> })}</tbody></table></div>{assignments.length === 0 ? <EmptyState icon={Users} title="No creators assigned" description="Activate community creators and divide this campaign’s content requirements." /> : null}</Panel>{assigning ? <AssignMemberModal campaign={campaign} onClose={() => setAssigning(false)} /> : null}</div> : null}
    {tab === 'content' ? <LeaderContentTable campaignId={campaign.id} /> : null}
    {tab === 'budget' ? <CampaignBudget campaign={campaign} /> : null}
  </div>
}

function AssignMemberModal({ campaign, onClose }: { campaign: CommunityCampaign; onClose: () => void }) {
  const { state, dispatch } = useApp()
  const metrics = getCommunityCampaignMetrics(state, campaign.id)
  const eligible = state.members.filter((item) => item.communityId === campaign.communityId && item.active && !state.assignments.some((assignment) => assignment.communityCampaignId === campaign.id && assignment.memberId === item.id))
  const [memberId, setMemberId] = useState(eligible[0]?.id ?? '')
  const [quantity, setQuantity] = useState(1)
  const remaining = campaign.contentQuota - metrics.assigned
  function submit(event: React.FormEvent) { event.preventDefault(); if (!memberId || quantity < 1 || quantity > remaining) return; dispatch({ type: 'ASSIGN_MEMBER', communityCampaignId: campaign.id, memberId, requiredContent: quantity }); onClose() }
  return <div className="modal-backdrop"><form className="modal-card compact-modal" onSubmit={submit}><header><div><span className="eyebrow">CREATOR ASSIGNMENT</span><h2>Assign content requirements</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></header><div className="form-grid"><label className="field"><span>Community creator</span><select aria-label="Community creator" value={memberId} onChange={(event) => setMemberId(event.target.value)}>{eligible.map((member) => <option key={member.id} value={member.id}>{member.name} · {member.handle}</option>)}</select></label><label className="field"><span>Required content</span><input aria-label="Assigned content quantity" type="number" min="1" max={remaining} value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /><small>{remaining} unassigned content slots remain.</small></label></div><footer><button type="button" className="button button-secondary" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={!memberId || quantity > remaining}>Assign creator</button></footer></form></div>
}

function LeaderContentTable({ campaignId }: { campaignId?: string }) {
  const { state, dispatch, community } = useLeaderContext()
  const [recordingId, setRecordingId] = useState<string | null>(null)
  const [recordingUrl, setRecordingUrl] = useState('')
  const campaignIds = new Set(state.communityCampaigns.filter((item) => item.communityId === community.id && (!campaignId || item.id === campaignId)).map((item) => item.id))
  const rows = [...state.contents].reverse().filter((item) => campaignIds.has(item.communityCampaignId) && ['Published', 'Recorded', 'Validated', 'Counted'].includes(item.status)).sort((a, b) => {
    const priority = (status: string) => ['Recorded', 'Validated'].includes(status) ? 0 : status === 'Published' ? 1 : 2
    return priority(a.status) - priority(b.status)
  }).slice(0, 60)
  function recordPublishedLink() {
    if (!recordingId || !recordingUrl.trim()) return
    dispatch({ type: 'RECORD_CONTENT', contentId: recordingId, publishedUrl: recordingUrl })
    setRecordingId(null)
  }
  return <><Panel title="Published content monitoring" description="Record published links; OkPo counts eligible content automatically."><div className="table-wrap"><table><thead><tr><th>Creator</th><th>Promotion</th><th>Status</th><th>Public link</th><th>Published</th><th>Supporting reach</th><th /></tr></thead><tbody>{rows.map((content) => { const member = state.members.find((item) => item.id === content.memberId)!; const campaign = state.communityCampaigns.find((item) => item.id === content.communityCampaignId)!; return <tr key={content.id}><td><div className="person-cell"><Avatar initials={member.initials} size="sm" /><span><strong>{member.name}</strong><small>Content {content.slot}</small></span></div></td><td>{campaign.title}</td><td><ContentBadge status={content.status} /></td><td>{content.publishedUrl ? <a className="table-link" href={content.publishedUrl} target="_blank" rel="noreferrer">Inspect post ↗</a> : '—'}</td><td>{content.publishedAt ?? '—'}</td><td>{formatNumber(content.views)} views</td><td>{['Recorded', 'Validated'].includes(content.status) ? <span className="yes-cell"><Check size={14} />Counting automatically</span> : content.status === 'Published' ? <button className="button button-secondary button-small" onClick={() => { setRecordingId(content.id); setRecordingUrl(content.publishedUrl ?? '') }}>Record link</button> : content.status === 'Counted' ? <span className="yes-cell"><Check size={14} />Counted</span> : <span className="muted">Waiting for publication</span>}</td></tr> })}</tbody></table></div></Panel>{recordingId ? <div className="modal-backdrop"><div className="modal-card compact-modal"><header><div><span className="eyebrow">COMMUNITY MANAGER CONTENT RECORD</span><h2>Record the published link</h2></div><button className="icon-button" onClick={() => setRecordingId(null)}>×</button></header><Callout tone="neutral" title="Published externally">Use the public post URL supplied by the creator. Recording does not publish or sync analytics.</Callout><label className="field"><span>Published-content URL</span><input aria-label="Manager published-content URL" value={recordingUrl} onChange={(event) => setRecordingUrl(event.target.value)} /></label><footer><button className="button button-secondary" onClick={() => setRecordingId(null)}>Cancel</button><button className="button button-primary" disabled={!recordingUrl.trim()} onClick={recordPublishedLink}>Record link</button></footer></div></div> : null}</>
}

function CampaignBudget({ campaign }: { campaign: CommunityCampaign }) {
  const { state, dispatch } = useApp()
  const rewards = state.rewards.filter((item) => item.communityCampaignId === campaign.id)
  const approved = rewards.filter((item) => ['Approved', 'Completed'].includes(item.status)).reduce((sum, item) => sum + item.amount, 0)
  return <div className="tab-stack"><section className="metrics-grid metrics-grid-three"><MetricCard label="Promotion earnings pool" value={formatCurrency(campaign.rewardBudget)} detail="fixed within community allocation" icon={WalletCards} /><MetricCard label="Approved or completed" value={formatCurrency(approved)} detail="simulated earnings status" icon={CheckCircle2} /><MetricCard label="Available" value={formatCurrency(Math.max(0, campaign.rewardBudget - approved))} detail="not yet released" icon={CircleDollarSign} /></section><Panel title="Creator earnings" description="Prototype statuses only—no payments are processed."><div className="table-wrap"><table><thead><tr><th>Creator</th><th>Content requirement</th><th>Earnings</th><th>Status</th><th /></tr></thead><tbody>{rewards.map((reward) => { const member = state.members.find((item) => item.id === reward.memberId)!; const assignment = state.assignments.find((item) => item.id === reward.assignmentId)!; return <tr key={reward.id}><td><div className="person-cell"><Avatar initials={member.initials} size="sm" /><strong>{member.name}</strong></div></td><td>{assignment.requiredContent}</td><td><strong>{formatCurrency(reward.amount)}</strong></td><td><StatusBadge status={reward.status} /></td><td>{reward.status === 'Pending' ? <button className="button button-secondary button-small" onClick={() => dispatch({ type: 'SET_REWARD_STATUS', rewardId: reward.id, status: 'Approved' })}>Approve earnings</button> : reward.status === 'Approved' ? <button className="button button-secondary button-small" onClick={() => dispatch({ type: 'SET_REWARD_STATUS', rewardId: reward.id, status: 'Completed' })}>Mark completed</button> : <span className="yes-cell"><Check size={14} />Complete</span>}</td></tr> })}</tbody></table></div></Panel></div>
}

export function LeaderMembers() {
  const { state, dispatch, community, campaigns } = useLeaderContext()
  const members = state.members.filter((item) => item.communityId === community.id)
  return <div className="page-stack"><PageHeader eyebrow="MY CREATORS" title="Activate and assign your creators" description={`${community.verifiedSize} verified creators underpin allocations; this prototype shows the active operational cohort.`} /><section className="metrics-grid metrics-grid-three"><MetricCard label="Verified community size" value={community.verifiedSize} detail="allocation basis" icon={BadgeCheck} /><MetricCard label="Active creators" value={members.filter((item) => item.active).length} detail={`${members.filter((item) => item.newlyRecruited).length} newly recruited`} icon={UserCheck} /><MetricCard label="Active promotions" value={campaigns.filter((item) => ['Preparation', 'Ready', 'Live'].includes(item.status)).length} detail="ready for assignments" icon={Layers3} /></section><Panel title="Creator roster"><div className="table-wrap"><table><thead><tr><th>Creator</th><th>Platform</th><th>Creator type</th><th>Assignments</th><th>Counted content</th><th>Status</th></tr></thead><tbody>{members.map((member) => { const assignments = state.assignments.filter((item) => item.memberId === member.id); const counted = state.contents.filter((item) => item.memberId === member.id && item.status === 'Counted').length; return <tr key={member.id}><td><div className="person-cell"><Avatar initials={member.initials} /><span><strong>{member.name}</strong><small>{member.handle}</small></span></div></td><td>{member.platform}</td><td><button className={member.newlyRecruited ? 'new-label member-type-button' : 'member-type-button'} onClick={() => dispatch({ type: 'SET_MEMBER_ACTIVE', memberId: member.id, active: member.active, newlyRecruited: !member.newlyRecruited })}>{member.newlyRecruited ? 'New recruit' : 'Mark as new recruit'}</button></td><td>{assignments.length}</td><td>{counted}</td><td><button className={`activation-toggle ${member.active ? 'active' : ''}`} onClick={() => dispatch({ type: 'SET_MEMBER_ACTIVE', memberId: member.id, active: !member.active })}><i />{member.active ? 'Active' : 'Inactive'}</button></td></tr> })}</tbody></table></div></Panel></div>
}

export function LeaderContent() {
  const { contents } = useLeaderContext()
  const counted = contents.filter((item) => item.status === 'Counted').length
  return <div className="page-stack"><PageHeader eyebrow="CONTENT MONITORING" title="From published link to counted delivery" description="Monitor your creators’ published content; OkPo handles counting automatically." /><section className="metrics-grid metrics-grid-two"><MetricCard label="Counted content" value={counted} detail="contributes to brand commitments" icon={CheckCircle2} tone="yellow" /><MetricCard label="Available views" value={formatNumber(contents.reduce((sum, item) => sum + item.views, 0))} detail="supporting metric only" icon={BarChart3} /></section><LeaderContentTable /></div>
}

export function LeaderBudget() {
  const { state, claims, campaigns } = useLeaderContext()
  const total = claims.reduce((sum, item) => sum + item.budgetAllocation, 0)
  const divided = campaigns.reduce((sum, item) => sum + item.rewardBudget, 0)
  const completedRewards = state.rewards.filter((reward) => campaigns.some((campaign) => campaign.id === reward.communityCampaignId) && reward.status === 'Completed').reduce((sum, item) => sum + item.amount, 0)
  return <div className="page-stack"><PageHeader eyebrow="COMMUNITY EARNINGS" title="Earnings across every promotion" description="Track earned, pending, and available community rewards. No real payments are processed." /><section className="metrics-grid metrics-grid-three"><MetricCard label="Total community earnings" value={formatCurrency(completedRewards)} detail="simulated completed rewards" icon={CircleDollarSign} tone="yellow" /><MetricCard label="Pending earnings" value={formatCurrency(Math.max(0, divided - completedRewards))} detail="across active promotions" icon={WalletCards} /><MetricCard label="Available campaign pool" value={formatCurrency(Math.max(0, total - divided))} detail={`${claims.length} campaign allocations`} icon={Layers3} /></section><Panel title="Earnings by campaign"><div className="table-wrap"><table><thead><tr><th>Brand campaign</th><th>Content quota</th><th>Allocated</th><th>Promotion earnings pool</th><th>Available</th></tr></thead><tbody>{claims.map((claim) => { const opportunity = state.opportunities.find((item) => item.id === claim.opportunityId)!; const related = campaigns.filter((item) => item.claimId === claim.id); const assigned = related.reduce((sum, item) => sum + item.rewardBudget, 0); return <tr key={claim.id}><td><strong>{opportunity.name}</strong><small className="table-subline">Claimed {claim.claimedAt}</small></td><td>{claim.contentQuota}</td><td><strong>{formatCurrency(claim.budgetAllocation)}</strong></td><td>{formatCurrency(assigned)}</td><td>{formatCurrency(claim.budgetAllocation - assigned)}</td></tr> })}</tbody></table></div></Panel></div>
}

export function LeaderCommunityProfile() {
  const { dispatch, community } = useLeaderContext()
  const [form, setForm] = useState<Community>(community)
  const [saved, setSaved] = useState(false)
  function submit(event: React.FormEvent) { event.preventDefault(); dispatch({ type: 'UPDATE_COMMUNITY', community: form }); setSaved(true) }
  return <div className="page-stack settings-page"><PageHeader eyebrow="COMMUNITY PROFILE" title="Your verified campaign community" description="Brands see this profile, while verified size powers automatic allocation." /><form className="panel profile-form" onSubmit={submit}><div className="profile-identity"><Avatar initials={form.initials} size="lg" tone="mint" /><div><strong>{form.name}</strong><span><BadgeCheck size={14} />Verified community</span></div><div className="profile-verified"><strong>{form.verifiedSize}</strong><small>verified creators</small></div></div><Callout tone="neutral" title="Verified size is read-only">OkPo’s internal administration verifies community size. Community Managers cannot edit the allocation basis in this prototype.</Callout><div className="form-grid form-grid-two"><label className="field"><span>Community name</span><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label className="field"><span>Location</span><input value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} /></label><label className="field"><span>Community Manager name</span><input value={form.leaderName} onChange={(event) => setForm({ ...form, leaderName: event.target.value })} /></label><label className="field"><span>Manager classification</span><select value={form.leaderType} onChange={(event) => setForm({ ...form, leaderType: event.target.value as Community['leaderType'] })}><option>Internal</option><option>External</option></select></label><label className="field full"><span>Community description</span><textarea rows={4} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label></div><footer className="form-footer">{saved ? <span className="saved-message"><CheckCircle2 size={16} />Saved to this prototype</span> : <span />}<button className="button button-primary">Save community profile</button></footer></form></div>
}
